name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t prometour-html .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag prometour-html ${{ secrets.DOCKER_USERNAME }}/prometour-html
          docker push ${{ secrets.DOCKER_USERNAME }}/prometour-html
