name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t pruebahtml .
          docker login -u pcmalaga -p dckr_pat_j7lRhqlXGiMpyua059S6HLBLXYE
          docker tag prometour-html pcmalaga/prometour-html
          docker push pcmalaga/prometour-html
